# THIS DOCKERFILE IS INTENDED FOR DEVELOPMENT ENVIRONMENTS
# DO NOT USE THIS FOR PRODUCTION USAGES.

version: "3.6"

services:
  pgDB:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      DB_HOST: host.docker.internal
      ALLOW_EMPTY_PASSWORD: yes
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  app:
    depends_on:
      - pgDB
    build: ./
    restart: unless-stopped
    environment:
      PSQL_HOST: pgDB
      DB_HOST: host.docker.internal
    ports:
      - "3500:3500"

volumes:
  db_data:
